/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as DqRouteImport } from './routes/dq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as ApiCrmContactRouteImport } from './routes/api/crm-contact'
import { Route as ApiCrmStageRouteImport } from './routes/api/crm-stage'
import { Route as ApiCustomRugPartialRouteImport } from './routes/api/custom-rug-partial'
import { Route as ApiMetaCapiRouteImport } from './routes/api/meta-capi'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'
import { Route as ApiPublicGoogleFeedDotxmlRouteImport } from './routes/api/public/google-feed[.]xml'
import { Route as ApiPublicMetaCatalogDotcsvRouteImport } from './routes/api/public/meta-catalog[.]csv'
import { Route as ApiPublicMetaCatalogDotxmlRouteImport } from './routes/api/public/meta-catalog[.]xml'
import { Route as ApiPublicDownloadSplatRouteImport } from './routes/api/public/download.$'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const DqRoute = DqRouteImport.update({
  id: '/dq',
  path: '/dq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmContactRoute = ApiCrmContactRouteImport.update({
  id: '/api/crm-contact',
  path: '/api/crm-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmStageRoute = ApiCrmStageRouteImport.update({
  id: '/api/crm-stage',
  path: '/api/crm-stage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomRugPartialRoute = ApiCustomRugPartialRouteImport.update({
  id: '/api/custom-rug-partial',
  path: '/api/custom-rug-partial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaCapiRoute = ApiMetaCapiRouteImport.update({
  id: '/api/meta-capi',
  path: '/api/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/catalogue/$slug',
  path: '/catalogue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleFeedDotxmlRoute =
  ApiPublicGoogleFeedDotxmlRouteImport.update({
    id: '/api/public/google-feed.xml',
    path: '/api/public/google-feed.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaCatalogDotcsvRoute =
  ApiPublicMetaCatalogDotcsvRouteImport.update({
    id: '/api/public/meta-catalog.csv',
    path: '/api/public/meta-catalog.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaCatalogDotxmlRoute =
  ApiPublicMetaCatalogDotxmlRouteImport.update({
    id: '/api/public/meta-catalog.xml',
    path: '/api/public/meta-catalog.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDownloadSplatRoute = ApiPublicDownloadSplatRouteImport.update({
  id: '/api/public/download/$',
  path: '/api/public/download/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/custom': typeof CustomRoute
  '/dq': typeof DqRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lookbook': typeof LookbookRoute
  '/privacy': typeof PrivacyRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/api/crm-contact': typeof ApiCrmContactRoute
  '/api/crm-stage': typeof ApiCrmStageRoute
  '/api/custom-rug-partial': typeof ApiCustomRugPartialRoute
  '/api/meta-capi': typeof ApiMetaCapiRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/api/public/google-feed.xml': typeof ApiPublicGoogleFeedDotxmlRoute
  '/api/public/meta-catalog.csv': typeof ApiPublicMetaCatalogDotcsvRoute
  '/api/public/meta-catalog.xml': typeof ApiPublicMetaCatalogDotxmlRoute
  '/api/public/download/$': typeof ApiPublicDownloadSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/custom': typeof CustomRoute
  '/dq': typeof DqRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lookbook': typeof LookbookRoute
  '/privacy': typeof PrivacyRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/api/crm-contact': typeof ApiCrmContactRoute
  '/api/crm-stage': typeof ApiCrmStageRoute
  '/api/custom-rug-partial': typeof ApiCustomRugPartialRoute
  '/api/meta-capi': typeof ApiMetaCapiRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/api/public/google-feed.xml': typeof ApiPublicGoogleFeedDotxmlRoute
  '/api/public/meta-catalog.csv': typeof ApiPublicMetaCatalogDotcsvRoute
  '/api/public/meta-catalog.xml': typeof ApiPublicMetaCatalogDotxmlRoute
  '/api/public/download/$': typeof ApiPublicDownloadSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/custom': typeof CustomRoute
  '/dq': typeof DqRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lookbook': typeof LookbookRoute
  '/privacy': typeof PrivacyRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/api/crm-contact': typeof ApiCrmContactRoute
  '/api/crm-stage': typeof ApiCrmStageRoute
  '/api/custom-rug-partial': typeof ApiCustomRugPartialRoute
  '/api/meta-capi': typeof ApiMetaCapiRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/api/public/google-feed.xml': typeof ApiPublicGoogleFeedDotxmlRoute
  '/api/public/meta-catalog.csv': typeof ApiPublicMetaCatalogDotcsvRoute
  '/api/public/meta-catalog.xml': typeof ApiPublicMetaCatalogDotxmlRoute
  '/api/public/download/$': typeof ApiPublicDownloadSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/craft'
    | '/custom'
    | '/dq'
    | '/explore'
    | '/faq'
    | '/how-it-works'
    | '/lookbook'
    | '/privacy'
    | '/story'
    | '/terms'
    | '/track-order'
    | '/api/crm-contact'
    | '/api/crm-stage'
    | '/api/custom-rug-partial'
    | '/api/meta-capi'
    | '/catalogue/$slug'
    | '/catalogue/'
    | '/api/public/google-feed.xml'
    | '/api/public/meta-catalog.csv'
    | '/api/public/meta-catalog.xml'
    | '/api/public/download/$'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/craft'
    | '/custom'
    | '/dq'
    | '/explore'
    | '/faq'
    | '/how-it-works'
    | '/lookbook'
    | '/privacy'
    | '/story'
    | '/terms'
    | '/track-order'
    | '/api/crm-contact'
    | '/api/crm-stage'
    | '/api/custom-rug-partial'
    | '/api/meta-capi'
    | '/catalogue/$slug'
    | '/catalogue'
    | '/api/public/google-feed.xml'
    | '/api/public/meta-catalog.csv'
    | '/api/public/meta-catalog.xml'
    | '/api/public/download/$'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/craft'
    | '/custom'
    | '/dq'
    | '/explore'
    | '/faq'
    | '/how-it-works'
    | '/lookbook'
    | '/privacy'
    | '/story'
    | '/terms'
    | '/track-order'
    | '/api/crm-contact'
    | '/api/crm-stage'
    | '/api/custom-rug-partial'
    | '/api/meta-capi'
    | '/catalogue/$slug'
    | '/catalogue/'
    | '/api/public/google-feed.xml'
    | '/api/public/meta-catalog.csv'
    | '/api/public/meta-catalog.xml'
    | '/api/public/download/$'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CraftRoute: typeof CraftRoute
  CustomRoute: typeof CustomRoute
  DqRoute: typeof DqRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LookbookRoute: typeof LookbookRoute
  PrivacyRoute: typeof PrivacyRoute
  StoryRoute: typeof StoryRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ApiCrmContactRoute: typeof ApiCrmContactRoute
  ApiCrmStageRoute: typeof ApiCrmStageRoute
  ApiCustomRugPartialRoute: typeof ApiCustomRugPartialRoute
  ApiMetaCapiRoute: typeof ApiMetaCapiRoute
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
  ApiPublicGoogleFeedDotxmlRoute: typeof ApiPublicGoogleFeedDotxmlRoute
  ApiPublicMetaCatalogDotcsvRoute: typeof ApiPublicMetaCatalogDotcsvRoute
  ApiPublicMetaCatalogDotxmlRoute: typeof ApiPublicMetaCatalogDotxmlRoute
  ApiPublicDownloadSplatRoute: typeof ApiPublicDownloadSplatRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dq': {
      id: '/dq'
      path: '/dq'
      fullPath: '/dq'
      preLoaderRoute: typeof DqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm-contact': {
      id: '/api/crm-contact'
      path: '/api/crm-contact'
      fullPath: '/api/crm-contact'
      preLoaderRoute: typeof ApiCrmContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm-stage': {
      id: '/api/crm-stage'
      path: '/api/crm-stage'
      fullPath: '/api/crm-stage'
      preLoaderRoute: typeof ApiCrmStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/custom-rug-partial': {
      id: '/api/custom-rug-partial'
      path: '/api/custom-rug-partial'
      fullPath: '/api/custom-rug-partial'
      preLoaderRoute: typeof ApiCustomRugPartialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-capi': {
      id: '/api/meta-capi'
      path: '/api/meta-capi'
      fullPath: '/api/meta-capi'
      preLoaderRoute: typeof ApiMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/catalogue/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-feed.xml': {
      id: '/api/public/google-feed.xml'
      path: '/api/public/google-feed.xml'
      fullPath: '/api/public/google-feed.xml'
      preLoaderRoute: typeof ApiPublicGoogleFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-catalog.csv': {
      id: '/api/public/meta-catalog.csv'
      path: '/api/public/meta-catalog.csv'
      fullPath: '/api/public/meta-catalog.csv'
      preLoaderRoute: typeof ApiPublicMetaCatalogDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-catalog.xml': {
      id: '/api/public/meta-catalog.xml'
      path: '/api/public/meta-catalog.xml'
      fullPath: '/api/public/meta-catalog.xml'
      preLoaderRoute: typeof ApiPublicMetaCatalogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$': {
      id: '/api/public/download/$'
      path: '/api/public/download/$'
      fullPath: '/api/public/download/$'
      preLoaderRoute: typeof ApiPublicDownloadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CraftRoute: CraftRoute,
  CustomRoute: CustomRoute,
  DqRoute: DqRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LookbookRoute: LookbookRoute,
  PrivacyRoute: PrivacyRoute,
  StoryRoute: StoryRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  ApiCrmContactRoute: ApiCrmContactRoute,
  ApiCrmStageRoute: ApiCrmStageRoute,
  ApiCustomRugPartialRoute: ApiCustomRugPartialRoute,
  ApiMetaCapiRoute: ApiMetaCapiRoute,
  CatalogueSlugRoute: CatalogueSlugRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
  ApiPublicGoogleFeedDotxmlRoute: ApiPublicGoogleFeedDotxmlRoute,
  ApiPublicMetaCatalogDotcsvRoute: ApiPublicMetaCatalogDotcsvRoute,
  ApiPublicMetaCatalogDotxmlRoute: ApiPublicMetaCatalogDotxmlRoute,
  ApiPublicDownloadSplatRoute: ApiPublicDownloadSplatRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
